name: gbans
main: lovetwice1012\gbans\Main
version: 1.7.0
api: 
  - 3.0.0
  - 4.0.0
auther: lovetwice1012

commands:
  gban:
    description: ユーザーをGbanします。
    usage: /gban username reason
    permission: op
  gunban:
    description: ユーザーのGbanを取り消します。
    usage: /gunban username
    permission: op
