name: gbans
main: lovetwice1012\gbans\Main
version: 1.5.0
api: 3.12.0
auther: lovetwice1012

commands:
  gban:
    description: 悪人よ。BANの鉄槌をくらえ！！
    usage: /gban username reason
    permission: op
  gunban:
    description: あ、悪人は君じゃなかったんだね…
    usage: /gban username
    permission: op
